export interface StyleOption {
    id: string;
    title: string;
    image: string;
    prompt: string;
    tags?: string[];
    category: "saude" | "direito" | "corporate" | "studio" | "outdoor" | "casual" | "editorial" | "cinematic" | "creative" | "noir" | "formatura" | "premium" | "lifestyle";
}

export const STYLES: StyleOption[] = [
    {
        id: "golden-crown",
        title: "Editorial Golden Crown",
        category: "editorial",
        tags: ["Golden", "Premium", "Crown", "Luxury"],
        image: "", // Placeholder
        prompt: `Ultra-realistic professional portrait of [person] wearing a refined golden crown, high-end editorial photography, luxury aesthetic, confident and powerful expression, sharp jawline lighting, soft but dramatic key light from the left, subtle rim light separating from background, dark charcoal background with smooth gradient, shallow depth of field, 85mm lens, f/1.8, cinematic color grading, high dynamic range, ultra detailed skin texture, natural skin tones, premium fashion magazine style, symmetrical composition, centered framing, 4K resolution, no distortion, no extra limbs, no text, no watermark`,
    },
    {
        id: "bw-cinematic-light",
        title: "Cinemático P&B com Luz Natural",
        category: "cinematic",
        tags: ["P&B", "Cinemático", "Luz Natural", "Retrato"],
        image: "",
        prompt: `A hyperrealistic 8K black and white cinematic mid shot portrait of this exact [person] in the image — same face, same identity, same facial features and proportions, natural textured skin, faint freckles, and slightly messy hair. He is standing near a tall window, framed from the waist up, his shoulders relaxed and hands loosely adjusting the collar of his shirt. His gaze drifts slightly past the camera, calm yet introspective. Soft, bright sunlight streams through blinds, casting blurred luminous rays across his face and torso. The light scatters into glowing streaks that resemble underwater reflections, wrapping around his body in a surreal pattern. Shadows are rendered in mid-gray tones instead of deep black, creating a smooth, filmic balance where highlights shine vividly while shadows remain soft and atmospheric. The details of skin are hyperrealistic — visible pores, light stubble, subtle imperfections — emphasized naturally by the glowing light beams. The folds of his shirt catch the rays, adding depth and realism to the texture. The background fades into soft gradients of gray with faint haze, while cinematic film grain overlays the image, giving it the texture of analog photography. The overall mood is intimate, timeless, and emotionally evocative — a monochrome editorial portrait where light itself becomes the central character.`,
    },
    {
        id: "high-end-studio",
        title: "Estúdio High-End",
        category: "studio",
        tags: ["Estúdio", "Profissional", "Luz Quente", "Cinemático"],
        image: "",
        prompt: `Transform this image into a cinematic, high-end studio-style portrait. Use a smooth orange-to-black gradient backdrop, creating the feel of a professional studio environment. Introduce subtle warm orange back glow behind the subject, gradually fading into a rich black tones to evoke depth and contrast. Apply soft, natural daylight-style white key lighting on the face, enhancing contours without altering the subject’s original appearance. Simulate professional quality of a Sony Alpha A7R III with a 35mm Helios lens, creating a creamy, shallow depth of field and delicate vintage-style bokeh around the body and background. Do not alter any facial features — the subject’s face, hair, skin texture, eyes, nose, lips, and glasses must remain entirely untouched. The identity and realism of the subject should be preserved completely. The transformation should focus only on lighting, atmosphere, and image quality to create a cinematic, gallery-grade portrait.`,
    },
    {
        id: "monochrome-refined",
        title: "Monocromático Refinado",
        category: "noir",
        tags: ["Monocromático", "Gola Alta", "Elegante", "Sério"],
        image: "",
        prompt: `A portrait of a confident [person] standing in a refined modern interior, wearing a black turtleneck, thin-rimmed glasses, with a sharp profile and perfect posture, his expression serious and composed, exuding discipline and visual sophistication, speaking rarely but always with precision, captured in soft directional indoor lighting to highlight facial structure and texture, shot with a Leica SL2, 90mm f/2 APO lens, monochrome palette with deep black and graphite tones.`,
    },
    {
        id: "corporate-headshot",
        title: "Retrato Corporativo",
        category: "studio",
        tags: ["Corporativo", "LinkedIn", "Terno", "Profissional"],
        image: "",
        prompt: `Ultra-realistic 8K corporate headshot of the person in the input photo. Keep their exact face, identity, age, gender, ethnicity, hairstyle and expression; do not alter unique facial features. Replace clothing with a tailored navy blue wool business suit and crisp white shirt. Clean dark gray studio backdrop with a soft center-light gradient and subtle vignette, no objects. Style as a Sony A7III 85mm f/1.4 studio portrait in portrait orientation with shallow depth of field: subject sharp, background softly blurred. Soft three-point lighting with gentle shadows and a subtle rim light on hair and shoulders. Preserve natural skin texture with pores and fine details, no plastic smoothing. Bright, natural catchlights in the eyes. Final image: high-end LinkedIn-ready studio portrait.`,
    },
    {
        id: "vibrant-nightlife",
        title: "Editorial Noturno",
        category: "editorial",
        tags: ["Vibrante", "Moda", "Elegante", "Descontraído"],
        image: "",
        prompt: `Ultra-realistic nightlife portrait, vertical composition, medium shot (waist-up). Subject smiles warmly, head tilted slightly, one arm bent with hand behind/over the head, relaxed confident vibe. Wardrobe: vibrant marigold/yellow tailored blazer over a matte black crew-neck tee; slim silver chain necklace; dark trousers. Grooming: neat full beard/stubble, clean edges; voluminous swept-back hair with soft texture; clear skin.`,
    },
    {
        id: "white-studio-professional",
        title: "Estúdio Clean",
        category: "studio",
        tags: ["Clean", "Branco", "Corporativo", "Terno Cinza"],
        image: "",
        prompt: `A professional portrait of a confident person standing against a clean white studio background. The person wears a fitted gray suit, white shirt, and blue tie, giving a formal yet approachable impression. Use soft daylight-style lighting from the right side to create gentle shadows and natural depth. The pose should be upright with hands clasped naturally in front and a relaxed smile. Render the image in photorealistic style with sharp focus, clean composition, and 85mm lens perspective. Keep the uploaded person’s facial features, proportions, and skin tone natural. The overall mood should feel bright, optimistic, and professional, suitable for a company profile, academic, or keynote speaker photo.`,
    },
    {
        id: "university-jacket",
        title: "Uniforme Universitário",
        category: "studio",
        tags: ["Universitário", "Jovem", "Casual Chic", "Estúdio"],
        image: "",
        prompt: `A 4:5 studio portrait of a young Indonesian man, half-body shot, standing facing forward with a slight, confident smile and wearing glasses. He is dressed in a dark blue university alma mater jacket worn over a white shirt and a dark tie. The front buttons of the jacket are open. The background is a plain light neutral grey with soft, diffused studio lighting and a subtle warm orange backlight. The image is ultra-realistic 8K resolution, with sharp focus on the eyes and a soft background blur.`,
    },
    {
        id: "executive-library",
        title: "Executivo na Biblioteca",
        category: "editorial",
        tags: ["Executivo", "Biblioteca", "Clássico", "Terno Elegante"],
        image: "",
        prompt: `A poised man sitting on a leather sofa in a refined office library. He wears a formal dark gray suit with a waistcoat and tie, maintaining an elegant yet relaxed posture. The background features wooden shelves lined with books, giving a cultured and executive atmosphere. The composition focuses on balance, posture, and expression blending confidence with calm professionalism. Realistic studio lighting, shallow depth of field, 8K detail, high-end corporate portrait photography.`,
    },
    {
        id: "dark-leather-studio",
        title: "Estúdio Sombrio em Couro",
        category: "cinematic",
        tags: ["Cinemático", "Terno 3 Peças", "Autoridade", "Escuro"],
        image: "",
        prompt: `A professional man sitting confidently on a classic leather armchair in a dark studio setting. He wears a tailored charcoal gray three-piece suit with a white shirt and black tie. The background is minimalist and elegant, highlighting the subject’s authority and composure. The lighting is cinematic and focused, creating depth and clarity on the facial expression. Emphasize the texture of the suit, the polished shoes, and the confident yet approachable demeanor. Ultra realistic, 8K, professional portrait photography, magazine cover style.`,
    },
    {
        id: "noir-keyhole",
        title: "Noir pelo Buraco da Fechadura",
        category: "noir",
        tags: ["Film Noir", "Dramático", "Terno Riscado", "Cinemático"],
        image: "",
        prompt: `Cinematic portrait of a man (given image) sitting confidently on a brown leather armchair, viewed through a blurred circular keyhole framing. The man wears a dark pinstripe suit and a white shirt, hands clasped in front, exuding calm authority. A single hanging warm lamp illuminates the scene from above, creating a moody, dramatic lighting effect with soft shadows and golden tones. Background is dark and minimal, evoking a film noir, editorial-style aesthetic. The composition feels introspective and stylish, with a subtle haze and cinematic depth of field. Style Keywords: cinematic lighting, editorial photography, moody tone, film noir, soft focus, warm glow, realistic portrait, dramatic composition, professional studio setup Camera Settings (optional additions): – 85mm lens, f/1.8, ISO 400, shallow depth of field, keyhole framing`,
    },
    {
        id: "minimalist-high-fashion",
        title: "Moda Minimalista",
        category: "studio",
        tags: ["Minimalista", "Moda", "Terno Customizado", "Moderno"],
        image: "",
        prompt: `Hyper-realistic portrait sitting on a tall stool in a minimalist studio. Wearing a charcoal-gray tailored suit with cropped trousers, high-collar blazer, and white sneakers. Arms crossed, leaning slightly forward, confident expression. Neutral background, ultra-detailed fabric textures, realistic lighting, fashion editorial quality.`,
    },
    {
        id: "sunlit-archway",
        title: "Arco Iluminado pelo Sol",
        category: "editorial",
        tags: ["Editorial", "Luz Solar", "Casual", "Linho"],
        image: "",
        prompt: `Analyze...: subject in sunlit archway, arms loosely crossed, eyes to camera, relaxed. Keep arm cross geometry. Angle lock: camera eye level, slight left pan; three-quarter body. Wardrobe: linen shirt, tan chinos. Lighting: hard side sunlight + bounce fill; background arch depth. Render 8k. Identity preserved. Shot R5 + 35mm f/4, ISO 100. Negative: no modifications.`,
    },
    {
        id: "modern-branding",
        title: "Branding Moderno",
        category: "studio",
        tags: ["Branding", "Moderno", "Contraste", "Estúdio Escuro"],
        image: "",
        prompt: `Modern branding photo in dark studio with controlled contrast. Subject sits square to camera, arms resting forward, face softly illuminated. Clothing black-on-white combination, matte textures only. Key light above-left, fill minimal, shadows deep yet refined. Gray seamless background with slight gradient halo behind subject. Lens 85 mm f/2 ISO 100. Color palette neutral and cinematic.`,
    },
    {
        id: "warm-brown-editorial",
        title: "Editorial Tons Quentes",
        category: "editorial",
        tags: ["Elegante", "Tons Quentes", "Suéter", "Luxury"],
        image: "",
        prompt: `Мужчина крупным планом на фоне тёплого коричневого градиента. Он сидит, слегка наклонившись вперёд, левая рука поднята к лицу и частично прикрывает щеку, запястье на уровне подбородка. На запястье — стильные часы с темно-синим циферблатом и ремешком из гладкой коричневой кожи, блестящим на мягком свете. Правая рука пересекает грудь, создавая выразительную позу. Мужчина в плотном кашемировом свитере глубокого кофейного оттенка, без принтов. Взгляд направлен прямо в камеру, выражение лица серьёзное, уверенное и немного задумчивое. Свет мягкий, направленный под углом, подчёркивает фактуру кожи, бороды и волос, создаёт лёгкие золотистые тени. Цветовая гамма — тёплая, с оттенками кофе, карамели и бронзы. Атмосфера — элегантная, мужественная, с эстетикой luxury men's editorial portrait. Кадр крупный, до плеч, фон гладкий, мягко размытый, подчёркивает глубину и стиль.`,
    },
    {
        id: "nano-banana-corporate",
        title: "Corporativo Futurista",
        category: "studio",
        tags: ["Corporativo", "Cubo de Luz", "Moderno", "Minimalista"],
        image: "",
        prompt: `/NANO BANANA PROMPT Inside a neutral cube of light, the designer sits on a tall wooden stool centered on a reflective concrete floor. Their outfit—white overshirt, beige cropped pants, minimalist sneakers—mirrors the architecture’s restraint. A hard key from high-right slices across the torso, drawing defined shadow on the opposite wall. The camera hovers level with the chest, perfectly parallel, yielding modern corporate composure. Background gradient transitions from platinum to ash, maintaining neutral value. Expression soft, thoughtful. The environment emits controlled energy, ready for publication or keynote visuals. Grading accentuates metallic gray mid-tones, preserving balanced whites. Captured in 8K UHD Canon R5 + 50 mm f/1.8 at f/3 ISO 100. Negative prompt forbids posture alteration, lighting color shift, wardrobe redesign, or compositional deviation—lock symmetry and high-contrast calm.`,
    },
    {
        id: "modern-office",
        title: "Escritório Moderno",
        category: "corporate",
        tags: ["Corporativo", "Office", "Luz Natural", "Liderança"],
        image: "",
        prompt: `Hyper-realistic 8K professional corporate portrait of [person] in a high-end modern office. Floor-to-ceiling windows showing a blurred cityscape. Subject is leaning against a minimalist white desk, wearing a tailored charcoal suit (or professional attire). Natural afternoon sunlight blending with soft indoor key lighting. Clean, organized environment with a soft bokeh. Identity and facial features preserved with maximum detail. 50mm f/1.8 landscape-style portrait.`,
    },
    {
        id: "urban-street",
        title: "Street Style Urbano",
        category: "outdoor",
        tags: ["Ar Livre", "Cidade", "Casual", "Moderno"],
        image: "",
        prompt: `Cinematic urban street portrait of [person] walking in a bustling city center at golden hour. Warm backlight creating a beautiful rim around the subject. Background features a busy street with motion-blurred cars and lights. The subject is wearing a high-quality leather jacket or stylish casual wear. Realistic skin textures and lighting. Captured on a Canon R5 with a 35mm lens, f/2.8.`,
    },
    {
        id: "coffee-shop-lifestyle",
        title: "Coffee Shop Lifestyle",
        category: "lifestyle",
        tags: ["Lifestyle", "Café", "Aconchegante", "Casual"],
        image: "",
        prompt: `Cozy lifestyle portrait of [person] sitting in a rustic, modern coffee shop. Holding a ceramic mug, slight smile, relaxed posture. Soft window light illuminating the face from the side. Background shows blurred coffee machines and wooden textures. Warm, inviting color palette with a film-like grain. Identity perfectly preserved. Fujifilm aesthetics, 50mm f/1.2.`,
    },
    {
        id: "neon-creative",
        title: "Criativo Neon Noir",
        category: "creative",
        tags: ["Criativo", "Neon", "Noite", "Artístico"],
        image: "",
        prompt: `Artistic creative portrait of [person] illuminated by vibrant pink and cyan neon lights. Dark, moody environment with reflections on a wet surface. Cyberpunk-inspired color grading. Subject has a confident and mysterious expression. Maximum sharpness on the eyes. High-contrast lighting with deep shadows. 4K, ultra-detailed textures.`,
    },
    {
        id: "editorial-brown-luxury",
        title: "Editorial Marrom Luxury",
        category: "editorial",
        tags: ["Editorial", "Marrom", "Luxury", "Relógio"],
        image: "",
        prompt: `Cinematic portrait, close-up (head and shoulders), vertical 4:5. [person] with a serious and confident expression, looking directly at the camera. Slightly leaning forward, head resting on the left hand. Left hand supports the face with a closed fist positioned below the chin. Right hand crosses the chest naturally, creating an introspective and elegant pose. Wearing a dark brown knit sweater (cashmere or fine wool), visible and sophisticated texture. On the left wrist, an elegant watch with a dark blue dial, refined metal case, and smooth brown leather strap. Background with a warm and soft brown gradient, completely blurred. Soft, side-directed lighting (soft key light), creating delicate shadows that highlight skin texture and facial volume. Predominant warm tones (brown, caramel, soft gold). Premium male editorial atmosphere. Photography setup: 85mm lens, f/2.0, shallow depth of field, sharp focus on the eyes, background with soft bokeh, high level of detail, natural skin texture, warm cinematic color grading, professional studio photography, ultra-realistic.`,
    },
    {
        id: "creator-tech-studio",
        title: "Estúdio Creator Tech",
        category: "creative",
        tags: ["Criativo", "Tech", "Workspace", "Neon"],
        image: "",
        prompt: `Cinematic portrait in a creative indoor environment, vertical 4:5, medium close-up (from the chest up). [person] with a neutral and confident expression, looking directly at the camera. Camera positioned at eye level, frontal framing with a very subtle 3/4 angle to add depth. 50mm or 85mm lens, f/1.8 aperture, shallow depth of field, extremely sharp focus on the eyes, background with soft bokeh and blurred lights. Cinematic mixed lighting: soft and warm main light coming from the side (warm key light), combined with cold ambient light in the background. Balanced contrast, skin with slightly warmed natural tones. Creative studio or workspace environment in the background, blurred, with colored lighting (blue, green, and orange tones), creating visual layers. Decorative elements and screens in the background out of focus, creating a modern and technological atmosphere. Minimalist clothing: plain black t-shirt, modern casual style. Contemporary aesthetic, creator/tech studio, ultra-realistic, high sharpness, subtle teal and orange cinematic color grading, professional photography 4k – 8k.`,
    },
    {
        id: "clean-corporate-modern",
        title: "Clean Corporativo Moderno",
        category: "corporate",
        tags: ["Corporativo", "Clean", "Moderno", "Sorridente"],
        image: "",
        prompt: `Clean and modern portrait, medium shot (waist-up), vertical 4:5 aspect ratio. [person] with a spontaneous and smiling expression, looking slightly up and away from the camera, conveying confidence and naturalness. Seated pose, body slightly leaning forward, forearms resting on the legs. Hands interlaced in front of the body. On the left wrist, a sophisticated metallic watch with a robust case. Camera positioned at chest height, slightly below the eye line (subtle low-angle), creating a sense of presence and proximity. 50mm or 85mm lens, f/2.0 aperture, moderate depth of field, sharp focus on the face, clean and slightly blurred background. Soft and diffused studio lighting, main front light slightly from the side, soft and natural shadows. No dramatic contrast. Neutral and balanced tones, skin with realistic and natural texture. Minimalist clothing: dark gray or graphite knit sweater, no prints. Black pants. Clean, corporate, and contemporary aesthetic. Light neutral background (off-white or light gray), minimalist environment without distracting elements. Professional photography, ultra-realistic, high sharpness, premium corporate portrait style, 4K – 8K.`,
    },
    {
        id: "artistic-minimalist-branding",
        title: "Artístico Minimalista Branding",
        category: "creative",
        tags: ["Artístico", "Minimalista", "Branding", "Studio"],
        image: "",
        prompt: `High-end artistic male portrait in a minimalist studio with neutral tones, subject seated and leaning slightly forward, hands visible resting near the face and chin, expression confident and approachable, extremely detailed skin texture across face and hands, soft large light source creating even illumination and gentle shadows, no harsh contrast, clean background, timeless professional look, ultra photorealistic personal branding portrait.`,
    },
    {
        id: "dark-neon-purple-artistic",
        title: "Estúdio Neon Roxo Artístico",
        category: "creative",
        tags: ["Criativo", "Neon Roxo", "Ambiental", "Dramático"],
        image: "",
        prompt: `Artistic ultra-realistic male bust portrait inside a dark neon studio environment, subject framed from mid-chest up with one hand resting naturally on the chin, relaxed shoulders and confident friendly expression, extremely detailed skin texture across face, neck and hands with visible pores, fine wrinkles and natural imperfections, soft diffused frontal key light creating smooth skin transitions, combined with a purple neon rim light outlining shoulders, jawline and fingers, subtle glow without overpowering realism, physically accurate subsurface scattering, dark background with soft purple haze, cinematic editorial mood for creative professionals.`,
    },
    {
        id: "creative-red-rim-branding",
        title: "Estúdio Rim Light Vermelho",
        category: "creative",
        tags: ["Criativo", "Rim Light", "Branding", "Impacto"],
        image: "",
        prompt: `Cinematic artistic male portrait inside a creative studio environment, subject seated with hands visible near the face, confident and sympathetic expression, ultra-detailed skin texture including realistic hand anatomy, soft diffused key light maintaining smooth tones, red neon rim light adding bold energy around silhouette, controlled highlights, dark modern background, high-impact branding portrait.`,
    },
    {
        id: "design-intellect-poise",
        title: "Intelecto e Postura Design",
        category: "studio",
        tags: ["Design", "Intelecto", "Minimalista", "Sério"],
        image: "",
        prompt: `Photorealistic portrait of [person] reflecting their physical characteristics with natural precision. Subject stands side-on to camera, face gently turned toward the light source. Strong top-left key light creates contour down nose and jaw. Rim highlight defines shoulder. Background deep graphite. Outfit monochrome dark jacket, neutral inner. Camera height mid-chest, straight-on. Image evokes design intellect and poise. High-end personal branding portrait.`,
    },
    {
        id: "beige-lifestyle-awais",
        title: "Criativo Beige Lifestyle",
        category: "lifestyle",
        tags: ["Lifestyle", "Criativo", "Bege", "Aconchegante"],
        image: "",
        prompt: `Mid-length portrait of [person] reflecting their identity and physical features accurately. Creative professional against smooth beige backdrop. Lighting soft and directional, highlighting contours and wardrobe texture. Subject seated comfortably, chin resting on fingers. Outfit tonal and sophisticated: white ribbed top, camel coat, khaki trousers. Mood serene, composition cinematic with shallow depth and warm highlights. Ultra-realistic detail.`,
    },
    {
        id: "matte-black-fullbody",
        title: "All Black Full-Body",
        category: "studio",
        tags: ["Full-Body", "All Black", "Minimalista", "Dramático"],
        image: "",
        prompt: `Full-body shot of [person] reflecting their physical proportions and features. Subject leans slightly on one leg, head tilted slightly down, expression neutral. Lighting high and left, projecting strong shadow behind and to side. Wardrobe matte black t-shirt, pants, shoes. Background seamless dark gray merging into black. Camera eye-level, lens 85mm f/2.8 ISO 100. Contrast bold; blacks deep, highlights measured. Professional photography.`,
    },
    {
        id: "gold-spotlight-navy",
        title: "Spotlight Dourado e Marinho",
        category: "cinematic",
        tags: ["Cinemático", "Spotlight", "Dourado", "Marinho"],
        image: "",
        prompt: `Moody portrait of [person] reflecting their physical characteristics with cinematic depth. The subject stands slightly off-center in front of a large, soft golden spotlight circle on a deep navy background. Use soft shadows and a cinematic feel. The subject wears a plain black t-shirt. Lighting falls from the top-left, casting a clear shadow to the right. Flawless skin texture, 4:3 aspect ratio, classic editorial portrait angle and distance. Professional studio lighting.`,
    },
    // --- NEW BATCH: PROFESSIONAL CATALOG ---
    {
        id: "medico-plantao",
        title: "Médico(a) de Plantão",
        category: "saude",
        tags: ["Saúde", "Plantão", "Scrub", "Hospital"],
        image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=400",
        prompt: `Portrait of [person] as a medical professional. Wearing a clean, fitted navy blue surgical scrub suit. Standing in a brightly lit, modern hospital hallway with slightly blurred background (bokeh). Expression is competent, approachable, and calm. Lighting is clean and even, imitating premium clinical environments. Highly detailed facial features and fabric texture.`,
    },
    {
        id: "medico-consultorio",
        title: "Médico(a) em Consultório",
        category: "saude",
        tags: ["Saúde", "Consultório", "Jaleco", "Elegante"],
        image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=400",
        prompt: `Portrait of [person] as an elite doctor. Wearing a tailored white lab coat over a smart-casual outfit (e.g., light blue shirt). Sitting at a premium oak desk in a high-end private clinic with soft natural light streaming from a window. Confident, reassuring smile. Shallow depth of field. High-end editorial photography.`,
    },
    {
        id: "advogado-tribunal",
        title: "Advogado(a) Corporativo",
        category: "direito",
        tags: ["Direito", "Terno", "Escritório", "Poder"],
        image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=400",
        prompt: `Portrait of [person] as a high-powered corporate lawyer. Wearing a sharp, perfectly tailored dark charcoal suit or blazer with a crisp white shirt. Standing confidently in a luxury glass-walled law firm office overlooking a city skyline at dusk. Dramatic side-lighting outlining the face to convey authority and intellect. Cinematic 85mm lens.`,
    },
    {
        id: "advogado-classic",
        title: "Advocacia Clássica",
        category: "direito",
        tags: ["Direito", "Gravata", "Clássico", "Estúdio"],
        image: "https://images.unsplash.com/photo-1556157382-97eda2d622ca?auto=format&fit=crop&q=80&w=400",
        prompt: `Classic studio portrait of [person] for a prestigious law firm profile. Wearing traditional formal legal attire (dark suit, subtle tie or elegant blouse). Background is a rich, mottled dark gray or brown backdrop. Lighting is traditional Rembrandt style, soft but defining. Expression is serious, trustworthy, and experienced. Extremely sharp focus.`,
    },
    {
        id: "night-office-intellect",
        title: "Intelecto no Escritório Noturno",
        category: "cinematic",
        tags: ["Cinemático", "Escritório", "Noite", "Foco"],
        image: "https://images.unsplash.com/photo-1507679799987-c7377f323b51?auto=format&fit=crop&q=80&w=400",
        prompt: `Cinematic editorial portrait of [person] reflecting their physical features. Seated at a dark wooden desk late at night. The subject leans slightly forward while writing on documents with a pen, one hand resting thoughtfully against the chin. Posture contemplative and focused, conveying intellectual concentration and quiet authority. Environment intimate and minimal: dim office setting with dark surroundings fading into shadow. A few open papers and documents spread across the desk surface. Background mostly black with subtle falloff, creating a dramatic studio-like atmosphere. Lighting low-key and directional, warm tungsten desk light coming from the front-left, illuminating the face, hands and papers while leaving the surrounding space in deep shadow. Soft highlight along the hair and cheekbone, gentle shadow across the jawline and neck. Contrast strong but controlled.`,
    },
    {
        id: "modern-navy-professional",
        title: "Profissional Moderno Marinho",
        category: "corporate",
        tags: ["Corporativo", "Marinho", "Moderno", "Confiança"],
        image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400",
        prompt: `Confident studio portrait of [person] reflecting their physical characteristics. Standing relaxed against a dark gradient backdrop. The subject faces the camera directly with a friendly, natural smile that conveys approachability and confidence. One hand rests casually inside a pocket while the other lightly holds the front of the jacket, posture upright yet relaxed. Wardrobe modern and refined: deep navy blue tailored blazer with subtle texture, paired with a clean black crew-neck shirt. Minimal accessories with a metallic wristwatch visible on the wrist, reinforcing a polished professional aesthetic. Background smooth charcoal-to-black gradient creating a clean studio environment with no visible distractions. Composition centered with balanced negative space around the subject. Lighting soft and directional from the front-left, producing gentle highlights across the face and jacket texture while maintaining natural skin tones. Camera positioned at chest height for a natural perspective. Framing mid-length portrait capturing upper torso and arms. Portrait lens look (85mm, shallow depth of field).`,
    },
    {
        id: "light-gray-executive",
        title: "Executivo Light Gray Trust",
        category: "corporate",
        tags: ["Corporativo", "Executivo", "Cinza", "Acessível"],
        image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400",
        prompt: `Professional studio portrait of [person] reflecting their physical characteristics. Middle-aged executive standing against a smooth light gray backdrop. The subject faces the camera with a relaxed, friendly smile, posture upright and composed. One arm crosses naturally across the torso while the opposite hand is raised near the chin in a subtle confident gesture, creating a composed and approachable professional stance. Wardrobe clean and modern: light gray tailored blazer over a crisp white dress shirt. Minimal accessories with a dark smartwatch visible on the wrist. Background neutral and seamless, soft light gray with no distractions. Lighting soft and balanced from the front-left, producing natural skin tones and gentle facial highlights while maintaining smooth shadows along the jawline and neck. Light wraps softly around the subject for a refined commercial portrait look. Camera positioned slightly above chest level. Framing upper-body portrait capturing head, shoulders and folded arms. Portrait lens look (85mm, shallow depth of field).`,
    },
    {
        id: "advogado-justica-estatua",
        title: "Advocacia e Justiça (Editorial)",
        category: "direito",
        tags: ["Direito", "Editorial", "Estátua", "Autoridade"],
        image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=80&w=400",
        prompt: `Editorial-style professional photograph of [person] reflecting their physical features. A lawyer working at a modern office desk. In the foreground, a detailed bronze statue of Lady Justice stands prominently on the desk, holding balanced scales and a sword. In the softly blurred background, [person] in formal attire (dark blazer and light shirt) sits at the desk focused on writing notes. Posture slightly leaned forward, conveying concentration and analytical thinking. Modern office environment, wooden desk, neutral gray textured wall. Soft natural lighting from the left. Shallow depth of field keeping the statue sharp while the subject remains softly diffused. Cinematic 85mm feel.`,
    },
    {
        id: "advogado-escrita-foco",
        title: "Advocacia em Foco (Documentos)",
        category: "direito",
        tags: ["Direito", "Foco", "Documentos", "Refinado"],
        image: "https://images.unsplash.com/photo-1505664194779-8beaceb93744?auto=format&fit=crop&q=80&w=400",
        prompt: `Professional editorial photograph of [person] reflecting their physical features. A lawyer working at a desk inside a modern office, writing with a pen on official documents. Expression focused and thoughtful. Wardrobe formal: dark tailored suit, white shirt, solid blue tie with clip, thin-framed eyeglasses. Background features a bookshelf filled with legal books, softly blurred. Soft balanced lighting from front-left. Medium portrait capturing upper torso, arms and desk environment. 85mm lens look.`,
    },
    {
        id: "advogado-confidente-mesa",
        title: "Advocacia Confidente (Mesa)",
        category: "direito",
        tags: ["Direito", "Confiança", "Corporativo", "Terno"],
        image: "https://images.unsplash.com/photo-1521791136064-7986c2959210?auto=format&fit=crop&q=80&w=400",
        prompt: `Professional corporate portrait of [person] reflecting their physical features. Seated at a modern office desk, facing camera with a composed, confident expression, hands calmly clasped together on the desk. Posture upright, conveying authority and trust. Wardrobe: dark navy business suit, white shirt, black tie. Desktop setup clean with keyboard and books. Background: wooden bookshelf with legal references, softly blurred. Eye-level perspective, medium portrait. 85mm lens look.`,
    },
    {
        id: "executivo-borda-mesa",
        title: "Executivo Premium (Borda da Mesa)",
        category: "premium",
        tags: ["Premium", "Executivo", "Poder", "Estúdio"],
        image: "https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&q=80&w=400",
        prompt: `Executive-style portrait of [person] reflecting their physical features. Confident professional seated on the edge of a wooden desk inside an elegant office. Calm, authoritative expression, posture upright and composed. One arm crosses forearm, hand relaxes on knee. Wardrobe: deep navy tailored suit, white shirt, classic wristwatch and minimal elegant accessories. Background: luxurious office wall with wooden shelving and warm ambient LED lighting. Cinematic and controlled lighting. 85mm lens look.`,
    },
    {
        id: "executivo-moderno-shelf",
        title: "Executivo Moderno (Backlit Shelf)",
        category: "premium",
        tags: ["Premium", "Moderno", "Liderança", "LED"],
        image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400",
        prompt: `Professional executive portrait of [person] reflecting their physical features. Standing beside a wooden desk in a modern office, approachable expression, relaxed posture. Wardrobe: tailored gray blazer, black crew-neck shirt. Office environment premium with open laptop. Background: wooden shelving wall with warm integrated LED lighting, globe, books, plants. Warm cinematic lighting with soft frontal key. Mid-thigh upward framing, 85mm lens look.`,
    },
    {
        id: "lideranca-determinacao",
        title: "Liderança e Determinação",
        category: "premium",
        tags: ["Premium", "Liderança", "Estratégia", "Foco"],
        image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&q=80&w=400",
        prompt: `Executive portrait of [person] reflecting their physical features. Leaning forward with both hands firmly placed on a wooden desk, determined expression. Posture conveys authority and strategic confidence. Wardrobe: deep navy tailored blazer, black dress shirt open at collar. Background: wooden shelving with warm integrated LED horizontal lines. Cinematic professional lighting, soft frontal key with golden ambient glow. Symmetrical composition, 85mm lens look.`,
    },
    {
        id: "senior-ceo-marble",
        title: "Senior CEO (Marble Prestige)",
        category: "premium",
        tags: ["Premium", "CEO", "Prestígio", "Mármore"],
        image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400",
        prompt: `Luxury executive portrait of [person] reflecting their physical features. Seated in a modern leather office chair behind a sleek desk, legs crossed, hands clasped. Composed, confident and authoritative expression. Wardrobe: tailored gray suit with subtle pattern, white shirt, dark tie, pocket square. Office environment luxurious: marble panel wall background with gray veining. Desk has laptop with charts. Cinematic controlled lighting. 85mm lens look, slightly low perspective to enhance presence.`,
    },
    {
        id: "advogado-sitting-led",
        title: "Advocacia Executive (Mãos na Mesa)",
        category: "direito",
        tags: ["Direito", "Liderança", "LED", "Madeira"],
        image: "https://images.unsplash.com/photo-1556157382-97eda2d622ca?auto=format&fit=crop&q=80&w=400",
        prompt: `Professional portrait of [person] reflecting their physical features. A confident lawyer sitting behind a wooden desk with hands clasped. Wearing an elegant navy tailored suit with a white dress shirt and burgundy tie. Accessories minimal and refined, including a classic wristwatch. Environment: Luxury law office interior with wooden shelves and warm LED lighting. Decor elements include law books and legal ornaments. Soft cinematic corporate lighting with warm ambient backlighting and a soft frontal key light. Shot on an 85mm portrait lens, shallow depth of field. Mood professional, trustworthy, authoritative.`,
    },
    {
        id: "advogado-standing-marble",
        title: "Advocacia Corporate (Mármore)",
        category: "direito",
        tags: ["Direito", "Mármore", "Corporativo", "Moderno"],
        image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=400",
        prompt: `Professional portrait of [person] reflecting their physical features. A confident lawyer standing beside a desk with arms relaxed. Wearing an elegant charcoal gray tailored suit with a light blue shirt and classic dark tie. Accessories minimal and refined, including a classic wristwatch. Environment: Luxury law office interior with a marble wall corporate office background. Decor elements include law books and sculptures. Soft cinematic corporate lighting with warm ambient backlighting and a soft frontal key light. Shot on an 85mm portrait lens, shallow depth of field. Mood professional, trustworthy, authoritative.`,
    },
    {
        id: "advogado-leaning-forward",
        title: "Advocacia Estratégica (Leaning)",
        category: "direito",
        tags: ["Direito", "Estratégia", "Foco", "Biblioteca"],
        image: "https://images.unsplash.com/photo-1505664194779-8beaceb93744?auto=format&fit=crop&q=80&w=400",
        prompt: `Professional portrait of [person] reflecting their physical features. A confident lawyer leaning forward with hands on the table. Wearing an elegant black tailored suit with a white dress shirt and classic dark tie. Accessories minimal and refined. Environment: Luxury law office interior with a modern law office background featuring legal books and wooden shelving. Soft cinematic corporate lighting with warm ambient backlighting and a soft frontal key light. Shot on an 85mm portrait lens, shallow depth of field. Mood determined, strategic, professional.`,
    },
    {
        id: "advogado-leather-library",
        title: "Advocacia Prestígio (Poltrona)",
        category: "direito",
        tags: ["Direito", "Prestígio", "Biblioteca", "Clássico"],
        image: "https://images.unsplash.com/photo-1575405273103-68d18409395f?auto=format&fit=crop&q=80&w=400",
        prompt: `Professional portrait of [person] reflecting their physical features. A confident lawyer seated in a leather chair with legs crossed. Wearing an elegant dark blue tailored suit with a white dress shirt and burgundy tie. Accessories minimal and refined, including a classic wristwatch. Environment: Luxury law office interior with a classic law firm library background featuring law books and sculptures. Soft cinematic corporate lighting with warm ambient backlighting and a soft frontal key light. Shot on an 85mm portrait lens, shallow depth of field. Mood authoritative, prestigious, trustworthy.`,
    },
    {
        id: "advogado-modern-minimal",
        title: "Advocacia Moderna (Sem Gravata)",
        category: "direito",
        tags: ["Direito", "Moderno", "Casual-Chic", "Liderança"],
        image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400",
        prompt: `Professional portrait of [person] reflecting their physical features. A confident lawyer standing with arms crossed. Wearing an elegant navy tailored suit with a light blue shirt and no tie for a modern, approachable legal look. Accessories include a classic wristwatch. Environment: Luxury law office interior with a minimal luxury office background. Decor elements include modern legal ornaments and wooden shelving. Soft cinematic corporate lighting with warm ambient backlighting and a soft frontal key light. Shot on an 85mm portrait lens, shallow depth of field. Mood professional, approachable, modern.`,
    },
    {
        id: "advogado-leaning-led",
        title: "Advocacia Dinâmica (Mão na Mesa)",
        category: "direito",
        tags: ["Direito", "Dinâmico", "LED", "Autoridade"],
        image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&q=80&w=400",
        prompt: `Professional portrait of [person] reflecting their physical features. A confident lawyer leaning forward with hands on the desk. Wearing an elegant charcoal gray tailored suit with a white dress shirt and classic dark tie. Accessories minimal and refined. Environment: Luxury law office interior with wooden shelves and warm LED lighting. Decor elements include legal ornaments and books. Soft cinematic corporate lighting with warm ambient backlighting and a soft frontal key light. Shot on an 85mm portrait lens, shallow depth of field. Mood authoritative, confident, professional.`,
    },
    {
        id: "medico-classic-consultorio",
        title: "Médico Especialista (Consultório)",
        category: "saude",
        tags: ["Saúde", "Consultório", "Clássico", "Jaleco"],
        image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=400",
        prompt: `Professional portrait of a confident medical doctor [person] reflecting their physical features, inside a modern medical clinic. The doctor wears a white medical coat over a light blue shirt with a stethoscope around the neck. Standing with arms crossed and a calm, approachable professional expression. Background shows a clean medical office with soft white lighting and blurred medical equipment. Soft natural clinical lighting creating a trustworthy and welcoming atmosphere. Shot with an 85mm portrait lens with shallow depth of field. Mood trustworthy, professional and empathetic.`,
    },
    {
        id: "medico-scrubs-hospital",
        title: "Médico de Plantão (Scrubs)",
        category: "saude",
        tags: ["Saúde", "Scrubs", "Hospital", "Plantão"],
        image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=400",
        prompt: `Professional portrait of a confident medical doctor [person] reflecting their physical features. Wearing blue surgical scrubs. Standing with arms crossed confidently. Background shows a hospital corridor softly blurred. Modern clinical environment, clean and minimal design emphasizing professionalism. Soft natural clinical lighting with bright neutral tones that create a trustworthy and professional medical atmosphere. Shot on an 85mm portrait lens, shallow depth of field. Mood professional, trustworthy and empathetic.`,
    },
    {
        id: "medico-consultation-files",
        title: "Consulta Médica (Foco)",
        category: "saude",
        tags: ["Saúde", "Consulta", "Foco", "Jaleco"],
        image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=400",
        prompt: `Professional portrait of a calm and confident medical doctor [person] reflecting their physical features. Sitting at a medical desk reviewing patient files in a medical consultation room. Wearing a white medical coat over a professional white dress shirt. Background features a clean white medical office with subtle medical instruments visible. Soft natural clinical lighting, bright neutral tones. Shot on an 85mm portrait lens, high-end medical branding photography style. Mood professional, trustworthy and analytical.`,
    },
    {
        id: "medico-tablet-modern",
        title: "Médico Tecnológico (Charts)",
        category: "saude",
        tags: ["Saúde", "Tech", "Tablet", "Moderno"],
        image: "https://images.unsplash.com/photo-1527613052228-8a897e77301f?auto=format&fit=crop&q=80&w=400",
        prompt: `Professional portrait of an approachable medical doctor [person] reflecting their physical features. Holding a tablet with medical charts inside a modern clinic interior. Wearing white medical coat with a stethoscope around the neck. Clean and minimal environment design emphasizing hygiene. Soft natural clinical lighting with bright neutral tones. Shot on an 85mm portrait lens, shallow depth of field. Mood modern, competent and technologically advanced.`,
    },
    {
        id: "medico-leaning-desk",
        title: "Médico Liderança (Mãos na Mesa)",
        category: "saude",
        tags: ["Saúde", "Liderança", "Mãos na Mesa", "Clínico"],
        image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400",
        prompt: `Professional portrait of a confident medical doctor [person] reflecting their physical features. Leaning slightly forward with hands on desk in a modern medical clinic. Wearing a white coat over a crisp shirt. Background shows a clinical environment with soft natural lighting. Minimal design emphasizing professionalism. Soft frontal key light illuminating the face. Shot on an 85mm portrait lens, shallow depth of field. Mood authoritative, trustworthy and professional.`,
    },
    {
        id: "medico-lab-research",
        title: "Médico Pesquisador (Lab)",
        category: "saude",
        tags: ["Saúde", "Laboratório", "Pesquisa", "Ciência"],
        image: "https://images.unsplash.com/photo-1576091160550-217359f4ecf8?auto=format&fit=crop&q=80&w=400",
        prompt: `Professional portrait of a focused medical doctor [person] reflecting their physical features in a laboratory environment. Wearing white medical coat over professional attire. Clean and minimal lab background emphasizing precision and professionalism. Soft natural clinical lighting with neutral tones. Shot on an 85mm portrait lens, shallow depth of field, high-end medical branding style. Mood analytical, competent and focused.`,
    },
    {
        id: "medico-exam-table",
        title: "Médico Acompanhamento (Exame)",
        category: "saude",
        tags: ["Saúde", "Exame", "Proximidade", "Cuidado"],
        image: "https://images.unsplash.com/photo-1551601651-2a8555f1a136?auto=format&fit=crop&q=80&w=400",
        prompt: `Professional portrait of a confident and approachable medical doctor [person] reflecting their physical features. Standing beside an examination table in a clean white medical office. Wearing white coat with a stethoscope. Soft natural clinical lighting that creates a trustworthy and professional atmosphere. Shot on an 85mm portrait lens, shallow depth of field. Mood empathetic, professional and welcoming.`,
    }
];

export const STYLE_CATEGORIES = [
    { id: "saude", label: "Área da Saúde", emoji: "🩺" },
    { id: "direito", label: "Advocacia", emoji: "⚖️" },
    { id: "corporate", label: "Corporativo", emoji: "💼" },
    { id: "studio", label: "Estúdio", emoji: "📷" },
    { id: "outdoor", label: "Ar Livre", emoji: "🌳" },
    { id: "casual", label: "Casual", emoji: "☕" },
    { id: "editorial", label: "Editorial", emoji: "🎨" },
    { id: "cinematic", label: "Cinemático", emoji: "🎬" },
    { id: "creative", label: "Criativo", emoji: "✨" },
    { id: "noir", label: "Noir", emoji: "🖤" },
    { id: "formatura", label: "Formatura", emoji: "🎓" },
    { id: "premium", label: "Premium", emoji: "⭐" },
    { id: "lifestyle", label: "Lifestyle", emoji: "☕" },
] as const;
